set_global_assignment -entity "SYSTEM_SYNC_PLL" -library "lib_SYSTEM_SYNC_PLL" -name IP_TOOL_NAME "altera_pll"
set_global_assignment -entity "SYSTEM_SYNC_PLL" -library "lib_SYSTEM_SYNC_PLL" -name IP_TOOL_VERSION "14.1"
set_global_assignment -entity "SYSTEM_SYNC_PLL" -library "lib_SYSTEM_SYNC_PLL" -name IP_TOOL_ENV "mwpim"
set_global_assignment -library "lib_SYSTEM_SYNC_PLL" -name SPD_FILE [file join $::quartus(sip_path) "SYSTEM_SYNC_PLL.spd"]

set_global_assignment -library "lib_SYSTEM_SYNC_PLL" -name MISC_FILE [file join $::quartus(sip_path) "SYSTEM_SYNC_PLL_sim/SYSTEM_SYNC_PLL.vho"]
